### ISSUE TITLE
milestone 3 comments

### ISSUE THREAD

**Issue by zeinalii** [ubco-W2020WT1-data301/course-project-solo_333#4]
## High priority (must-fix)

- [ ] Printing the dataset alone does not explain the data. You need to add a section called dataset, and explain the data. What are the columns and what do they show?

- [ ] add a structure to your report. It is better to have an introduction that gives the reader some information about the data and your question. 

- [ ] Just graphs alone do not answer your questions. You need to explain how those visualizations answer your questions. Try to explain the plots.

- [ ] Where are your questions? how are you going to answer them? add your questions.
